### ISSUE TITLE
Lack of anchor points for U+025B U+0190

### ISSUE THREAD

**Issue by andjc** [jobosonchisa/ojuju#11]
Combining diacritics  with combining classes 220 and 230 mispositioned on U+025B and U+0190, possibly anchor points missing on base glyphs. Impacts a number of African languages. Including Dinka and Nuer languages.

<img width="486" alt="Screen Shot 2024-03-08 at 14 19 54" src="https://github.com/jobosonchisa/ojuju/assets/1468027/bf7356a7-3db1-428a-8574-8ae9eb252fa9">

**Comment by bghryct** [comment]
@andjc same with the other issues we'll get these sorted this week. Thanks!

**Comment by bghryct** [comment]
This should be resolved now @andjc 
Please let me know if you're still finding issues in the new files.
