### ISSUE TITLE
Issues with Eng (U+014A and U+014B)

### ISSUE THREAD

**Issue by andjc** [jobosonchisa/ojuju#12]
There are two issues with the Eng glyphs that impact on a range of African languages:

1. The glyph shape used for the uppercase character (U+014A)
2. Lack of anchor points for glyphs of U+014A and U+014B

<img width="486" alt="Screen Shot 2024-03-08 at 14 39 51" src="https://github.com/jobosonchisa/ojuju/assets/1468027/8cbf547f-7618-4c65-b4cf-743bf2377b02">

There is a wide diversity in glyph shapes for U+014A, but there are two primary shapes, usually referred to as the N-form and the n-form. The existing glyph is the N-form, and the shape of the glyph is based on the shape used for the letter __N__. This glyph is used in some of the Sami languages, the Yolŋu languages, and various others.

African languages prefer the n-form, where the shape is based on the lowercase letter __n__ and usually has a descender and hook below the baseline. Although occasionally you find a version where the hook sits on the baseline.

Some African languages will also use diacritics with U+014A and U+014B. Currently, correct rendering of combining diacritics fail when U+014A or U+014B are base characters.

**Comment by bghryct** [comment]
@andjc  I'll resolve this this week. Thanks again!

**Comment by bghryct** [comment]
@andjc resolving this today. Propagating the changes to the google font will take more time but the new files today in the fonts folder the v1.001 will be corrected.

**Comment by bghryct** [comment]
this should be resolved now
