### ISSUE TITLE
Anchor points for ‎U+01DD

### ISSUE THREAD

**Issue by andjc** [jobosonchisa/ojuju#13]
Incorrectly positioned non-spacing marks on U+01DD. Does not affect uppercase character, only lowercase character.

<img width="486" alt="Screen Shot 2024-03-10 at 12 43 13" src="https://github.com/jobosonchisa/ojuju/assets/1468027/25a60b42-1222-4fec-82fc-52b4324eb4f2">

**Comment by bghryct** [comment]
@andjc Thanks for the excellent bug reporting. I'll take a look at all of your issues and get these resolved this week with @jobosonchisa and then we'll send an update to google fonts.

**Comment by bghryct** [comment]
resolved
