### ISSUE TITLE
Ojuju typeface designs

### ISSUE THREAD

**Issue by LisaHuang2017** [jobosonchisa/ojuju#2]
[Ojuju_Lisa_notes_231130.pdf](https://github.com/jobosonchisa/ojuju/files/13515526/Ojuju_Lisa_notes_231130.pdf)

Here are some comments about the shapes and details of Ojuju typeface (as of it status on Nov 17, 2023), mostly on page 1:
1. [x] The ear of r seems a bit too high, even with some overshoot above the x-height level.
2. [x] Looking at h, n and m, and how these have a corner more "pulled" to the top-right, it might be interesting to have that on b (and p), which will bring more consistency? 
3. [x] Ojuju has a strong "boxy" look, and the s could benefit in having an even stronger personality with that boxy look too, no?
4. [x] Letter t seems odd with that curved stem in ExtraLight, and it is even more odd because it is not like such in ExtraBold master.
5. [x] Letter i could be narrower
6. [x] Same with v. If you place it next to u, v looks super wide.
7. [x] I believe that shortening the middle bar of E and F will bring more balance to these.
8. [x] Have you tried to make the base of V a bit narrower? It could make V less of a confusable to U.
9. [x] Same boxy look on capital S as the lowercase s?
10. [x] Lowercase x looks quite wide, and the capital doesn't so much anymore. Both could be more closely related. 
11. [x] The tail of Q goes too far on the descender level.
12. [x] There is more work to do on the spacing, and looking at the spacing strings, I believe that more spacing on the right side of letters like a (maybe also d, and left side of b, n, m, etc.) would be more helpful.

Other notes on following pages are mainly about spacing and kerning, and some suggestions on proportions and lettershapes.

Question about Ojuju Medium: This style has a top-heavy / bottom-light weight distribution that others don't. Is is because it is still a test? Have you decided which direction you want to do to?

**Comment by tphinney** [comment]
@LisaHuang2017 please split these into 12 separate issues. Each is an item that could be done or debated. 

But if one WERE going to put them in one issue, you could use the checkbox function in Github, which you can do by starting a line with a dash square bracket, space, square bracket like this `- 1 [ ]` which renders like:
- 1 [ ] this

**Comment by LisaHuang2017** [comment]
[Ojuju_fb_Lisa_060124.pdf](https://github.com/jobosonchisa/ojuju/files/13850549/Ojuju_fb_Lisa_060124.pdf)

Updated feedback based on the Glyphs file of Ojuju from Jan. 5, 2024.
LIGHT WEIGHT
- [ ] make sure for design consistency on the curves terminals (C, G, J, S, Y, etc.)
- [ ] S : top could be slightly wider for better top / bottom balance
- [ ] alpha : maybe remove the bottom right (almost) serif? 
- [ ] IJ ligature : these letters should be closer. It is either a matter of spacing of each letter, or design another J in this ligature?
- [ ] Germandbls : it has to look different (more like a capital letter) than the lowercase variant
- [ ] t : why does the top of t looks different on the t's with diacritics?
- [ ] figures : 4, 7 and 9 would benefit of more adjustments for better balance
- [ ] asterisk : it doesn't look like it is from the same typeface (style too different!)

- [ ] Spacing issues are marked with plus and minus signs on each side of the letters that need adjustment (issue mentioned in #8 )

  - [ ] Diacritics on the capitals : they could be wider to be more legible, and have less contrast. Some are not correctly aligned with the letter
  - [ ] ogonek : the ogonek has to seem like it is "growing" from the bottom right part of the letter (ogonek is also mentioned in issue #4 
  - [ ] Diacritics on the lowercase : if the dot of the i is the reference, every other diacritics should be aligned with it (the dot is also a diacritic)
  
BOLD WEIGHT
- [ ] K : could be narrower
- [ ] Q : tail can be lighter
- [ ] S : can be more "boxy" to go better with the overall design
- [ ] Gstroke and Hbar : you can reduce the weight of certain parts of the letter when there are combinations with a bar so there is enough white space for the counter
- [ ] currency strokes : be careful with the positioning of the strokes and their consistency of thickness across every other currency symbols
